import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

type TokenLeaf = { value: string }
type TokenNode = { [key: string]: TokenNode | TokenLeaf }

function isLeaf(node: TokenNode | TokenLeaf): node is TokenLeaf {
  return typeof (node as TokenLeaf).value === 'string'
}

function flatten(node: TokenNode | TokenLeaf, prefix: string): [string, string][] {
  if (isLeaf(node)) return [[prefix, node.value]]
  return Object.entries(node).flatMap(([key, child]) => {
    const segment = key === 'DEFAULT' ? prefix : prefix ? `${prefix}-${key}` : key
    return flatten(child, segment)
  })
}

const tokens: TokenNode = JSON.parse(readFileSync(resolve(root, 'tokens.json'), 'utf-8'))

const vars = Object.entries(tokens).flatMap(([group, node]) =>
  flatten(node as TokenNode, group)
)

const lines = vars.map(([name, value]) => `  --${name}: ${value};`)
const output = `/* generated by scripts/build-tokens.ts — do not edit */\n@theme {\n${lines.join('\n')}\n}\n`

const outPath = resolve(root, 'frontend/src/styles/tokens.css')
writeFileSync(outPath, output, 'utf-8')
console.log(`wrote ${vars.length} tokens → ${outPath}`)
